server:
  port: 8080  

spring:
  config:
    import: optional:classpath:application-secret.yml
  datasource:
    url: jdbc:mariadb://192.168.0.224:3306/gaebalfan_erp
    username: root
    password: 9927
    driver-class-name: org.mariadb.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.gaebalfan.erp.domain
  configuration:
    map-underscore-to-camel-case: true

ocr:
  python:
    cmd: python
  project:
    path: C:/Users/3class_013/Desktop/main_project/MainProjectOCR

logging:
  level:
    root: WARN
    com.gaebalfan.erp: DEBUG
    org.mybatis: DEBUG
    org.springframework.web.servlet: DEBUG
    org.springframework.security: WARN